# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd4b1b4edcfc197bfe78ea6012147c79111f1ebd922454097a748d4730592dace7616fd7e9d30e46608dc966eb8bc7fcbe30bda951557b58c0c9fc78440cc398

test:
  secret_key_base: a969f25a8def827af34191689bfbb38768b3b28e12a54da111307e6ffe5bf99673b1927c2f09db44e2672fd926b82f8eb745860a001273eab85b2c70046bd659

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
